title: Elvis Dominguez
email: elvisd7z@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Elvis Dominguez, a.k.a. elvisd7z, personal github pages website.
  This could be my blog or whatever.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  elvisd7z

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
  social_links:
    - { platform: mastodon, user_url: "https://fosstodon.org/@elvisd7z" }
    - { platform: github, user_url: "https://github.com/elvisd7z" }